// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Stock.Web.Data;
using System;

namespace Stock.Web.Migrations
{
    [DbContext(typeof(StockContext))]
    partial class StockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Stock.Web.Data.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProductId");

                    b.Property<int>("Quantity");

                    b.Property<int>("VarietyId");

                    b.HasKey("BatchId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VarietyId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Stock.Web.Data.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ProductName");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Stock.Web.Data.ProductStock", b =>
                {
                    b.Property<int>("ProductStockID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProductId");

                    b.Property<int>("Quantity");

                    b.Property<int>("VarietyID");

                    b.HasKey("ProductStockID");

                    b.HasIndex("ProductId");

                    b.HasIndex("VarietyID");

                    b.ToTable("ProductStocks");
                });

            modelBuilder.Entity("Stock.Web.Data.Variety", b =>
                {
                    b.Property<int>("VarietyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("VarietyId");

                    b.ToTable("Varieties");
                });

            modelBuilder.Entity("Stock.Web.Data.Batch", b =>
                {
                    b.HasOne("Stock.Web.Data.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stock.Web.Data.Variety", "Variety")
                        .WithMany("Batches")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stock.Web.Data.ProductStock", b =>
                {
                    b.HasOne("Stock.Web.Data.Product", "Product")
                        .WithMany("ProductStocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stock.Web.Data.Variety", "Variety")
                        .WithMany("ProductStocks")
                        .HasForeignKey("VarietyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
